---
version: '3.7'
services:
  zk:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "2181"
    ports:
      - "2181:2181"
    command:
      - /opt/kafka/bin/zookeeper-server-start.sh
      - /opt/kafka/config/zookeeper.properties
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9092"
    ports:
      - "9092:9092"
    command:
      - /opt/kafka/bin/kafka-server-start.sh
      - /opt/kafka/config/server.properties
      - --override
      - listeners=PLAINTEXT://:9092
    volumes:
      - type: bind
        source: ./config/docker-compose-server.properties
        target: /opt/kafka/config/server.properties
    depends_on:
      - zk
